version: 2.1
## TestWhenOnFail  rollback attempt 1

defaults: &defaults   ## anchor & aliases
    docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run: npm i
    - save_cache: 
        key: "npm-packages"
        paths:
            - /src/node/modules
    - run: npm run lint

  test:
    <<: *defaults
    steps:
    - checkout
    - restore_cache: 
        keys: "npm-packages"
    - run: npm i    
    - run: npm run test
    
    
  analyse:   
    <<: *defaults
    steps:
    - checkout
    - restore_cache: 
        keys: "npm-packages"
    - run: npm audit   

workflows:
  BuildTestAnalyse-Jobs:
    jobs:
      - build
      - test:
          requires: 
           - build
      - analyse
          requires: 
           - test


